services:
  analytics-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: analytics-service
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
